Fix a linking error in the IP26 kernel. This is a regression caused by the addition of db_save_stack_trace().
sys/arch/mips64/mips64/trap.c:(.text+0x410): undefined reference to `u_intr'

Pointed out by deraadt@